import StyledComponentsRegistry from '@/components/config/registry';
import AuthSession from '@/components/config/Session';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body>
        <AuthSession>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </AuthSession>
      </body>
    </html>
  );
}
